accounts/urls.py
from django.conf.urls import patterns, include, url
from accounts.views import *

urlpatterns = patterns('',
    url(r'^login/', login, name='login'),
    url(r'^add_user/', add_user, name='add_user'),
    url(r'^register/', register, name='register'),
    (r'^register_success/', register_success),
    url(r'^pc_login/', 'django.contrib.auth.views.login', name='pc_login'),
    url(r'^logout/', logout_page, name='logout'),
    url(r'^user/(\w+)/$', user_page, name='user_page'),
)

bookmarks/urls.py
from django.conf.urls import *
from bookmark_base.views import *

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^photos/', include('photos.urls', namespace='photos')),
    (r'^accounts/', include('accounts.urls', namespace='accounts')),

    (r'^$', home),



    (r'^save/$', addmarks),
    (r'^tag/([^\s]+)/', tagpage),
    (r'^tag/$', tagcloundpage),
    (r'^search/$', search),

    (r'^friends/(\w+)/$', friendspage),
    (r'^friend/add/$', addfriend),
    (r'^vote/$', addvote),
    (r'^store/$', storeurl),
    (r'^delete/$', deleteurl),
    (r'^comments/$', include('django.contrib.comments.urls')),
    (r'^bookmark/(\d+)/$', bookmarkpage),
)

photos/urls.py
from django.conf.urls import *
from photos.views import *

urlpatterns = patterns('',
    url('upload/', add_photo)
)

bookmark_base/models.py
from django.db import models
from django.contrib.auth.models import User


class Url(models.Model):
    url = models.URLField(unique=True)

    def __unicode__(self):
        return self.url


class Bookmark(models.Model):
    title = models.CharField(max_length=100)
    uname = models.ForeignKey(User)
    link = models.ForeignKey(Url)

    def __unicode__(self):
        return u'%s , %s' % (self.uname.username, self.link.url)


class Tag(models.Model):
    content = models.CharField(max_length=100, unique=True)
    book = models.ManyToManyField(Bookmark)

    def __unicode__(self):
        return self.content


class ShareItem(models.Model):
    bookmark = models.ForeignKey(Bookmark)
    datetimeField = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=1)
    uvote = models.ManyToManyField(User)


class Freindship(models.Model):
    fromuser = models.ForeignKey(User, related_name='friend_set')
    touser = models.ForeignKey(User, related_name='to_friend_set')

    class Meta:
        unique_together = (('fromuser', 'touser'),)

accounts/forms.py
from django import forms
import re
from django.contrib.auth.models import User


class RegisteForm(forms.Form):
    username = forms.CharField(label=u'Username', max_length=30)
    email = forms.EmailField(label=u'Email')
    password1 = forms.CharField(
        label=u'Password',
        widget=forms.PasswordInput()
    )
    password2 = forms.CharField(
        label=u'Password Again',
        widget=forms.PasswordInput()
    )

    def clearpassword2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords not match')

    def clearusername(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("username can't contains not alpha or number")
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('username already exits')


class BookmarkForm(forms.Form):
    url = forms.URLField(
        label=u'URL',
        widget=forms.TextInput(attrs={'size': 100})
    )
    title = forms.CharField(
        label=u'Title',
        widget=forms.TextInput(attrs={'size': 100})
    )
    tag = forms.CharField(
        label=u'Tag',
        required=False,
        widget=forms.TextInput(attrs={'size': 100})
    )
    share = forms.BooleanField(
        label=u'share on the main page',
        required=False
    )


class SearchForm(forms.Form):
    query = forms.CharField(
        label=u'',
        widget=forms.TextInput(attrs={'size': 36})
    )

templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>网络收藏夹 - yuermarks书签</title>
    <meta name="description" content="yourmarks书签是免费的网址收藏夹，它可以帮助您收藏网址，并与朋友分享。"/>
    <meta name="keywords" content="yourmarks,书签,网络,网址,收藏夹,"/>
    {% load staticfiles %}
    <link rel="stylesheet" href="{{ STATIC_URL }}style.css" type="text/css"/>
    <script type="text/JavaScript" src="{{ STATIC_URL }}jquery.js"></script>
    {% block external %}{% endblock %}
    <style type="text/css">
        div#container{
        width:600px;
        margin:0 auto;
        }
        div#sign-in{
        width:800px;
        margin:0 auto;
        }
    </style>
</head>
<body class="narrowlook beforelogin">
<div id="container">
    <div id="header">
        <h1><a href="/"><img src="{{ STATIC_URL }}img/bg/1.png"/></a></h1>

        <div id="navigation" class="ui-rounderbox">
            <div class="ui-roundedbox-corner ui-roundedbox-tl">
                <div class="ui-roundedbox-corner ui-roundedbox-tr">
                    <div class="ui-roundedbox-corner ui-roundedbox-bl">
                        <div class="ui-roundedbox-corner ui-roundedbox-br">
                            <div class="ui-roundedbox-content">
                                <ul>
                                    {% if user.is_authenticated %}
                                    <li><a href="/">首页</a></li>
                                    <li><a href="{% url 'accounts:user_page' user.username %}">{{user.username}}</a></li>
                                    <li><a href="/friends/{{user.username}}/">好友</a></li>
                                    <li><a href="/save">收藏新网址</a></li>
                                    <li><a href="/search">搜索</a></li>
                                    <li><a href="{% url 'accounts:logout' %}">退出</a></li>
                                        {% else %}
                                    <li><a href="/">首页</a></li>
                                    <li><a href="/search">搜索</a></li>
                                    <li><a href="{% url 'accounts:login' %}">登录</a></li>
                                    <li><a href="{% url 'accounts:register' %}">注册</a></li>
                                        {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% block title %}{% endblock %}
{% block content %}{% endblock %}
<style type="text/css">
    #footer{
    text-align: center;
    margin: 30px 0 0 0;
    text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
    font-size:17px;
    }
</style>
<div id="footer">
    &copy; 2011 yuermarks
</div>
</body>
</html>

templates/bookmark_list1.html
{% if bookmarks %}
  <ul class="bookmarks">
    {% for bookmark in bookmarks %}
      <li>
        <a href="{{ bookmark.link.url }}" class="title">
          {{ bookmark.title }}</a>
        {% if show_edit %}
          <a href="/save/?url={{ bookmark.link.url|urlencode }}"
            class="edit">[edit]</a>
        {% endif %}
        <br />
        {% if show_tags %}
          Tags:
          {% if bookmark.tag_set.all %}
            <ul class="tags">
              {% for tag in bookmark.tag_set.all %}
                <li><a href="/tag/{{ tag.name|urlencode }}/">
                  {{ tag.name }}</a></li>
              {% endfor %}
            </ul>
          {% else %}
            None.
          {% endif %}
          <br />
        {% endif %}
        {% if show_user %}
          Posted by:
          <a href="/user/{{ bookmark.user.username }}/"
            class="username">
            {{ bookmark.user.username }}</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% if show_paginator %}
    <div class="paginator">
      {% if has_prev %}
        <a href="?page={{ prev_page }}">&laquo; Previous</a>
      {% endif %}
      {% if has_next %}
        <a href="?page={{ next_page }}">Next &raquo;</a>
      {% endif %}
      (Page {{ page }} of {{ pages }})
    </div>
  {% endif %}
{% else %}
  <p>No bookmarks found.</p>
{% endif %}

templates/bookmark_page.html
<style type="text/css">
#li-f{
height:22px;
margin-left:1.3cm;
font-size:24px;
}

#li-i {
border-bottom:1px dashed #cccccc;    
margin-left:1.3cm;
margin-right:55px;     
font-size:24px;
height:30px;  
}
strong{
height:22px;
margin-left:1.3cm;
font-size:24px;
}
#shux{
height:22px;
margin-left:1.3cm;
font-size:16px;
}
.nos ul{
list-style:none;
}
</style>

{% extends "base.html" %}
{% load comments %}
{% block title %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>Bookmark:{{ shared_bookmark.bookmark.title }}</h2>
{% endblock %}
{% block content %}
  Posted By:
  <a href="/user/{{ shared_bookmark.bookmark.uname.username }}/"
     class="username">
    {{ shared_bookmark.bookmark.uname.username }}</a> |
  <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>

  <h2>Comments</h2>
  {% get_comment_count for bookmark_base.shareitem shared_bookmark.id as comment_count %} 
  {% get_comment_list for bookmark_base.shareitem shared_bookmark.id as comment_list %} 

  {% for comment in comment_list %}
    <div class="comment">
      <p><b>{{ comment.user.username }}</b> said:</p>
      {{ comment.comment|urlizetrunc:40|linebreaks }}
    </div>
  {% endfor %}
  <p>Number of comments: {{ comment_count }}</p>

  {% render_comment_form for bookmark_base.shareitem shared_bookmark.id %} 
{% endblock %}

templates/bookmark_save.html
{%extends "base.html" %}
{% block title %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>添加书签</h2>
{% endblock %}
{% block content %}
{% include "bookmark_save_form.html" %}
</div></div></div></div></div></div> </div>
{% endblock %}

templates/bookmark_save_form.html
<style type="text/css">
#lab{
margin-left:1.3cm;
font-size:18px;
}
#formbutton1{height:23px;
padding:0 1.5em;
border:1px solid;
border-color:#66acff #094fa1 #094fa1 #66acff;
background:#2680e9;
color:#fff;
letter-spacing:.3em;
cursor:pointer;
line-height:23px;
margin-left:1.3cm;
}
#kuang{
margin-left:1.3cm;
size:100px;
}
</style>
<form id="save-form" method="post" action="/save/" class="lf">
{% csrf_token%}
<p><label  id="lab" class="label_input" for="id_url">网址:</label>
<div id="kuang">{{form.url}}</div></p>
<p><label  id="lab" class="label_input" for="id_title">标题:</label>
<div id="kuang">{{form.title}}</div></p>
<p><label  id="lab" class="label_input" for="id_tag">标签:</label>
<div id="kuang">{{form.tag}}</div></p>
<p><label  id="lab" class="label_input" for="id_share">共享:</label>
<div id="kuang">{{form.share}}</div></p>
<!--{{ form.as_p }}-->
<input type="submit" value="save"  id="formbutton1"/>
</form>

templates/friends.html
 
{% extends "base.html" %}
{% block title %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>{{ username }}'Friend List</h2>{% endblock %}
{% block content %}
  {% if friends %}
    <ul class="friends">
      {% for friend in friends %}
        <strong><a href="/user/{{ friend.username }}/">{{ friend.username }}</strong></li>
      {% endfor %}
    </ul>
  {% else %}
    <strong>No friends found.</strong>
  {% endif %}

  <h2>Latest Friend Bookmarks</h2>
  {% include "bookmark_list.html" %}
  </div></div></div></div></div></div> </div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>
欢迎您来到yuermarks网络书签，
记录精彩网址！</h2>
{%include "share_bookmark_list.html"%}
</div></div></div></div></div></div> </div>
{% endblock %}

templates/mainpage.html
{% extends "base.html"%}

{% block content %}
{% if user.username %}
<p>{{user.username}} , welcome to yourmarks!
Here you can store you bookmarks anywhere and anytime!
</p>
{% else %}
<p>you want to store bookmarks,please login first<a href="/login">login</a>
</P>
{% endif %}
{% endblock %}

templates/reg_success.html
{%extends "base.html" %}
{% block title %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>注册成功！</h2>
{% endblock %}
{% block content %}
</div></div></div></div></div></div> </div>
{% endblock %}

templates/search.html
{% extends "base.html"%}
{%block title%}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>书签搜索</h2>
{% endblock%}
{%block external%}
<script type="text/javascript" src="/media/search.js">
</script>
{%endblock%}
{%block content%} 
<style type="text/css">
#search-form{margin-left:1.3cm;}
</style>
<form id="search-form" method="get" action="." class="vf lf" >
{{form.as_p}}
<input type="submit" value="search" class="formbutton"/ >
</form>
<div id="search-results">
{%if show_result%}
{% include "bookmark_list.html" %}
{%endif%}
</div>
</div></div></div></div></div> </div>
{%endblock%}

templates/share_bookmark_list.html
<style type="text/css">
#li-i {
border-bottom:1px dashed #cccccc;    
margin-left:1.3cm;
margin-right:55px;     
font-size:15px;
height:30px;  
}
strong{
margin-left:1.3cm;
margin-right:22px;
font-size:24px;
height:22px;
}
#shux{
height:22px;
margin-left:1.3cm;
font-size:16px;
}
</style>
{% if shares %}
<ul class="bookmarks">
{% for share in shares %}
<strong>
<a href="/store/?id={{share.id}}">
{% load staticfiles %}
<img height="18" width="18" class="like_in" title="star" src="{{ STATIC_URL }}img/star.png"></a>
<a href="{{share.bookmark.link.url}}" class="title">
{{share.bookmark.title}}</a>
<a href="/vote/?id={{share.id}}">
<img class="like_in" title="like it! " src="{{ STATIC_URL }}img/like.gif"></a>
<!--<a href="/bookmark/{{share.id}}">
<img height="18" width="18" class="comments" title="comment" src="/static/img/com.gif"></a>-->
</strong>
{% if show_tags %}
{% if share.bookmark.tag_set.all %}
<ul class="tags">
<div id="shux">tags:
{% for tag in share.bookmark.tag_set.all %}
<a href="/tag/{{tag.content}}">{{tag.content}}</a>
{% endfor%}
</div>
</ul>
{%else%}
None
{% endif %}
{%endif%}
{% if show_user %}
<div id="shux">Posted by:
<a href="/user/{{share.bookmark.uname.username}}/" class="username">
{{share.bookmark.uname.username}}</a>
{% endif %}
<img class="like_in" title="votes " src="{{ STATIC_URL }}img/vote.gif"></a>
{{share.votes}}</div>
<div id="li-i" style="border-top:1px  ;height: 1px;overflow:hidden"></div>
{% endfor%}
</ul>
{% else%}
<strong>No bookmark found.</strong>
{% endif %}

templates/tag_clound_page.html
{% extends "base.html" %}
{% block title %}
<h2>Tag Clound</h2>
{% endblock %}

{% block content %}
{% if tags %}
{% for tag in tags %}
<li><a href="{{tag.content}}">{{tag.content}}</a> X {{tag.count}}</li>
{% endfor %}
{% else %}
no tags.
{% endif %}
{% endblock%}

templates/tag_page.html
{% extends "base.html"%}
{% block title %}
<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
<h2>Tag:{{ tag_name }}</h2>
{% endblock %}
{% block content %}
{% include "bookmark_list.html" %}
</div></div></div></div></div></div> </div>
{% endblock %}

templates/user_page.html
 
{% extends "base.html"%}
{% block external%}
<script type="text/javascript" src="{{ STATIC_URL }}bk.js">
</script>
{% endblock%}
{%block title%}<div id="sign-in" class="ui-roundedbox">
<div class="ui-roundedbox-corner ui-roundedbox-tl">
<div class="ui-roundedbox-corner ui-roundedbox-tr">
<div class="ui-roundedbox-corner ui-roundedbox-bl">
<div class="ui-roundedbox-corner ui-roundedbox-br">
<div class="ui-roundedbox-content"> 
{% endblock%}
{%block content%}
<div id="info">
<div id="avatar">
<a href="/user/{{user.username}}" title="">
<img src="{{ STATIC_URL }}img/touxiang.png" alt="" title="" /></a>
</div>
<div id="panel">
<h1>{{username}}</h1>
<!--<p class="actions"><a href="/friend.add/lydon" class="post_act bh" token="499f85eb"></a>-->
{% ifequal user.username username %}
  {% else %}
    {% if is_friend %}
      <a href="/friends/{{ user.username }}/" class="post_act bh">
查看{{username}} </a> 
    {% else %}
      <a href="/friend/add/?username={{ username }}" class="post_act bh">
       关注此人</a> 
    {% endif %}
{% endifequal %}
</div>
</div> 
{% include "bookmark_list.html"%}
</div></div></div></div></div></div> </div>
{%endblock%}